# Базовые параметры настройки конфигурации проекта
dbname: postgres # В классе менять не надо
user: public # Замените на свой логин от БД в классе
password: 12345 # Замените на свой пароль от БД в классе
host: 192.168.0.48 # Замените на 192.168.0.48 в классе
dbtableprefix: "public."  # Замените на свой логин от БД